apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: template-exchange
spec:
  name: template-exchange
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: ping-queue
spec:
  name: ping-queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: pong-queue
spec:
  name: pong-queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: ping-binding
spec:
  source: template-exchange
  destination: ping-queue
  routingKey: "ping-queue"
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: pong-binding
spec:
  source: template-exchange
  destination: pong-queue
  routingKey: "pong-queue"
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq
