[project]
name = "public-gateway-setup-job"
version = "0.1.0"
description = "Sets up ScyllaDB schema for the subsystem."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scylla-driver>=3.28.2",
]
