# call exchange
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: create-profile-rpc-call-exc
spec:
  name: creqte-profile-rpc-call-exc
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

# response exchange
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: create-profile-rpc-resp-exc
spec:
  name: create-profile-rpc-resp-exc
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

# call queue
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: create-profile-rpc-call-q
spec:
  name: create-profile-rpc-call-q
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

# create-profile-rpc-call-exc -> create-profile-rpc-call-q
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: create-profile-rpc-call-bind
spec:
  source: create-profile-rpc-call-exc
  destination: create-profile-rpc-call-q
  routingKey: "create-profile-rpc-call-q"
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq