apiVersion: batch/v1
kind: Job
metadata:
  name: image-upload-setup-job
  namespace: image-upload
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: image-upload-setup-job
    spec:
      restartPolicy: Never
      containers:
        - name: image-upload-setup-job
          image: image-upload-setup-job:latest
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /home/user1/.cache/uv
              name: uv
            - mountPath: /tmp
              name: temp
          env:
            - name: SCYLLADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: image-upload-user-scylla-creds
                  key: username
            - name: SCYLLADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-upload-user-scylla-creds
                  key: password
            - name: SCYLLADB_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: image-upload-keyspace
                  key: keyspace
      volumes:
        - emptyDir: {}
          name: uv
        - emptyDir: {}
          name: temp
