apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-2
  template:
    metadata:
      labels:
        app: example-service-2
    spec:
      containers:
        - name: example-service-2
          image: example-service-2:latest
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-service-2-rabbitmq-user-user-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-service-2-rabbitmq-user-user-credentials
                  key: password
            - name: SCYLLADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: template-user-scylla-creds
                  key: username
            - name: SCYLLADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: template-user-scylla-creds
                  key: password
            - name: SCYLLADB_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: template-keyspace
                  key: keyspace

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: example-service-2-rabbitmq-user
spec:
  tags:
  - policymaker
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: example-service-2-rabbitmq-permission
spec:
  vhost: "/"
  userReference:
    name: "example-service-2-rabbitmq-user"
  permissions:
    write: "template-exchange"
    configure: ""
    read: "pong-queue"
  rabbitmqClusterReference:
    name: rabbitmq

