apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-2
  namespace: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-2
  template:
    metadata:
      labels:
        app: example-service-2
    spec:
      containers:
        - name: example-service-2
          image: example-service-2:latest
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /home/user1/.cache/uv
              name: uv
            - mountPath: /tmp
              name: temp
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-service-2-rabbitmq-user-user-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-service-2-rabbitmq-user-user-credentials
                  key: password
            - name: SCYLLADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: template-user-scylla-creds
                  key: username
            - name: SCYLLADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: template-user-scylla-creds
                  key: password
            - name: SCYLLADB_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: template-keyspace
                  key: keyspace
      volumes:
        - emptyDir: {}
          name: uv
        - emptyDir: {}
          name: temp

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: example-service-2-rabbitmq-user
  namespace: template
spec:
  tags:
  - policymaker
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: example-service-2-rabbitmq-permission
  namespace: template
spec:
  vhost: "/"
  userReference:
    name: "example-service-2-rabbitmq-user"
  permissions:
    write: "ping-rpc-(call-exc|resp-q-.*)"
    configure: "ping-rpc-resp-(exc|q-.*)"
    read: "ping-rpc-resp-(exc|q-.*)"
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
