[project]
name = "example-service"
version = "0.1.0"
description = "The second example service, which sends messages to the first example service."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
    "valkey>=6.1.0",
]
