[project]
name = "change-auth"
version = "0.1.0"
description = "Handles changing a factor of authentication."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
]
