apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-2
  template:
    metadata:
      labels:
        app: example-service-2
    spec:
      containers:
        - name: example-service-2
          image: localhost:5000/example-service-2:latest
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-service-2-user-user-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-service-2-user-user-credentials
                  key: password

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: example-service-2-user
spec:
  tags:
  - policymaker
  rabbitmqClusterReference:
    name: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: example-service-2-permission
spec:
  vhost: "/"
  userReference:
    name: "example-service-2-user"
  permissions:
    write: "example-services-exchange"
    configure: ""
    read: ""
  rabbitmqClusterReference:
    name: rabbitmq

