apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  service:
    type: NodePort
