apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: scylla
data:
  scylla.yaml: |
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer

---

apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: dev-db
  namespace: scylla
spec:
  agentVersion: 3.3.0@sha256:dc2684f51e961d88da5a8eac2d9f165cb7a960cbf91f67f49332e7224317c96b
  version: 6.1.1
  developerMode: true
  exposeOptions:
    nodeService:
      type: ClusterIP
    broadcastOptions:
      clients:
        type: ServiceClusterIP
      nodes:
        type: ServiceClusterIP
  datacenter:
    name: dev-1
    racks:
      - name: dev-1a
        scyllaConfig: scylla-config
        members: 1 
        storage:
          capacity: 5Gi
        resources:
          requests:
            cpu: 400m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
