apiVersion: custom.local/v1
kind: ScyllaUser
metadata:
  name: listings-user
  namespace: listings
spec:
  scyllaClusterReference: dev-db

---

apiVersion: custom.local/v1
kind: ScyllaKeyspace
metadata:
  name: listings-keyspace
  namespace: listings
spec:
  scyllaClusterReference: dev-db
  replicationFactor: 3

---

apiVersion: custom.local/v1
kind: ScyllaPermission
metadata:
  name: listings-permission
  namespace: listings
spec:
  scyllaClusterReference: dev-db
  user: listings-user
  keyspace: listings-keyspace
  permission: CREATE
