[project]
name = "public-gateway"
version = "0.1.0"
description = "Exposes services to users."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hypercorn>=0.17.3",
    "pika>=1.3.2",
    "quart>=0.20.0",
    "scylla-driver>=3.28.2",
    "valkey>=6.1.0",
]
