[project]
name = "delete-message"
version = "0.1.0"
description = "Deletes a specific message"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
]
