apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-image
  namespace: image-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-image
  template:
    metadata:
      labels:
        app: report-image
    spec:
      containers:
        - name: report-image
          image: report-image:latest
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /home/user1/.cache/uv
              name: uv
            - mountPath: /tmp
              name: temp
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: report-image-rabbitmq-user-user-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: report-image-rabbitmq-user-user-credentials
                  key: password
            - name: SCYLLADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: image-upload-user-scylla-creds
                  key: username
            - name: SCYLLADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-upload-user-scylla-creds
                  key: password
            - name: SCYLLADB_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: image-upload-keyspace
                  key: keyspace
      volumes:
        - emptyDir: {}
          name: uv
        - emptyDir: {}
          name: temp

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: report-image-rabbitmq-user
  namespace: image-upload
spec:
  tags:
  - policymaker
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: report-image-rabbitmq-permission
  namespace: image-upload
spec:
  vhost: "/"
  userReference:
    name: "report-image-rabbitmq-user"
  permissions:
    write: ""
    configure: ""
    read: ""
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
