[project]
name = "create-food-item"
version = "0.1.0"
description = "user creates private food item to track"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
]
