[project]
name = "send-message"
version = "0.1.0"
description = "Service to send messages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
]
