apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-message
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-message
  template:
    metadata:
      labels:
        app: send-message
    spec:
      containers:
        - name: send-message
          image: send-message:latest
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /home/user1/.cache/uv
              name: uv
            - mountPath: /tmp
              name: temp
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: send-message-rabbitmq-user-user-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: send-message-rabbitmq-user-user-credentials
                  key: password
            - name: SCYLLADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-user-scylla-creds
                  key: username
            - name: SCYLLADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-user-scylla-creds
                  key: password
            - name: SCYLLADB_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: chat-keyspace
                  key: keyspace
      volumes:
        - emptyDir: {}
          name: uv
        - emptyDir: {}
          name: temp

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: send-message-rabbitmq-user
  namespace: chat
spec:
  tags:
  - policymaker
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: send-message-rabbitmq-permission
  namespace: chat
spec:
  vhost: "/"
  userReference:
    name: "send-message-rabbitmq-user"
  permissions:
    write: "sendmessage-rpc-resp-exc"
    configure: ""
    read: "send-message-rpc-call-q"
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
