[project]
name = "valkey-auth-operator"
version = "0.1.0"
description = "Creates and manages users for Valkey clusters."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kubernetes>=32.0.0",
    "valkey>=6.1.0",
]
