[project]
name = "delete-account"
version = "0.1.0"
description = "Handles deleting an account."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "scylla-driver>=3.28.2",
]
