name: Pylint

on: [push, workflow_call]

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and configure uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        cache-dependency-glob: |
          **/pyproject.toml
          **/poetry.lock
          **/requirements*.txt
    - name: Install dependencies and Pylint
      run: |
        python -m pip install --upgrade pip
        for file in $(git ls-files '**/pyproject.toml'); do
          dir=$(dirname "$file")
          echo "Installing dependencies in $dir"
          pushd "$dir"
          uv pip install --system . --cache-dir "$RUNNER_TEMP/uv_cache"
          popd
        done
        uv pip install --system pylint --cache-dir "$RUNNER_TEMP/uv_cache"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
