name: Testing

on: [pull_request]

permissions:
  actions: read
  contents: read

jobs:
  pylint:
    uses: ./.github/workflows/pylint.yml
  test:
    needs: [pylint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y make python3-pip curl

      - name: Install Python tools
        run: pip3 install uv

      - name: Install krew
        run: |
          (
            set -x; cd "$(mktemp -d)" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz" &&
            tar zxvf krew-linux_amd64.tar.gz &&
            KREW=./krew-linux_amd64 &&
            "$KREW" install krew
          )
          echo "$HOME/.krew/bin" >> $GITHUB_PATH

      - name: Install krew plugins
        run: |
          kubectl krew install rabbitmq
          kubectl krew install wait-job

      - name: Verify installations
        run: |
          docker --version
          docker buildx version
          kubectl version --client
          minikube version
          uv --version

      - name: Deploy
        run: make deploy -j8

      - name: Run tests
        run: make test-unchecked
